export const oldMoneyTheme = {
  base: "vs" as const,
  inherit: false,
  rules: [
    { token: "", foreground: "2C2824", background: "FDFCF9" },
    { token: "comment", foreground: "887870", fontStyle: "italic" },
    { token: "keyword", foreground: "2C5038", fontStyle: "bold" },
    { token: "string", foreground: "6B3320" },
    { token: "number", foreground: "A67C2E" },
    { token: "type", foreground: "1C2E4A" },
    { token: "function", foreground: "2C5038" },
    { token: "variable", foreground: "2C2824" },
    { token: "operator", foreground: "A67C2E" },
    { token: "delimiter", foreground: "887870" },
    { token: "tag", foreground: "2C5038" },
    { token: "attribute", foreground: "A67C2E" },
  ],
  colors: {
    "editor.background": "#FDFCF9",
    "editor.foreground": "#2C2824",
    "editor.lineHighlightBackground": "#F0EBE3",
    "editor.selectionBackground": "#A67C2E30",
    "editor.inactiveSelectionBackground": "#A67C2E18",
    "editorCursor.foreground": "#A67C2E",
    "editorLineNumber.foreground": "#C8BDB0",
    "editorLineNumber.activeForeground": "#A67C2E",
    "editorGutter.background": "#F9F6F0",
    "editorWidget.background": "#F5F0E8",
    "editorWidget.border": "#E0D8CC",
    "editorSuggestWidget.background": "#FDFCF9",
    "editorSuggestWidget.border": "#E0D8CC",
    "editorSuggestWidget.selectedBackground": "#F0EBE3",
    "scrollbarSlider.background": "#C8BDB040",
    "scrollbarSlider.hoverBackground": "#A67C2E40",
    "minimap.background": "#F5F0E8",
  },
};
